const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const FLAG = '$RNFirebaseDisableSPM = true';

/**
 * react-native-firebase v22+ resolves firebase-ios-sdk through Swift Package
 * Manager by default. Its SPM products are automatic (not `type: .dynamic`),
 * so under `use_frameworks! :linkage => :static` — which this app needs — each
 * Firebase pod embeds its own copy and they collide as duplicate symbols:
 *
 *   [react-native-firebase] SPM + static linkage is not supported
 *
 * Setting $RNFirebaseDisableSPM before the target block makes the pods resolve
 * Firebase through CocoaPods instead, which linkes statically without clashing.
 * This has to be a config plugin rather than a hand edit: ios/ is gitignored
 * and regenerated by every `expo prebuild`, which would drop a manual change.
 */
module.exports = function withRNFirebaseDisableSPM(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfilePath, 'utf8');
      if (!contents.includes(FLAG)) {
        fs.writeFileSync(podfilePath, `${FLAG}\n${contents}`);
      }
      return cfg;
    },
  ]);
};
